import Vue from 'vue'
import {
  InfiniteScroll,
  Scrollbar,
  // Skeleton,
  SkeletonItem,
  //  Descriptions,
  DescriptionsItem,
  // Tabs,
  TabPane,
  // Carousel,
  CarouselItem,
  Tooltip,
  Loading,
  MessageBox,
  Notification,
  Message
} from 'element-ui'

import {
  Alert,
  Anchor,
  AnchorItem,
  Aside,
  Avatar,
  Backtop,
  Badge,
  Breadcrumb,
  BreadCrumbItem,
  Button,
  ButtonGroup,
  Calender,
  Card,
  Carousel,
  // CarouselItem,
  Cascader,
  CascaderPanel,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Collapse,
  CollapseItem,
  Container,
  DatePicker,
  Descriptions,
  // DescriptionsItem,
  Dialog,
  Divider,
  Drawer,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Empty,
  Footer,
  Form,
  FormItem,
  Header,
  Image,
  ZleInfiniteScroll,
  Input,
  InputNumber,
  Link,
  Main,
  NavMenu,
  PageHeader,
  Pagination,
  Popconfirm,
  Popover,
  Progress,
  Radio,
  RadioGroup,
  RadioButton,
  Rate,
  Result,
  Row,
  Col,
  Select,
  Option,
  OptionGroup,
  Skeleton,
  ZleSkeletonItem,
  Slider,
  Statistic,
  Steps,
  Switch,
  Table,
  TableColumn,
  Tabs,
  // TabPane,
  Tag,
  Timeline,
  TimelineItem,
  TimePicker,
  TimeSelect,
  ZleTooltip,
  Transfer,
  Tree,
  Upload,
  Autocomplete
} from 'zl-element'
import '@/style/type/element-variables.scss' // element主题配置样式

const components = [
  // Skeleton,
  SkeletonItem,
  // Descriptions,
  DescriptionsItem,
  // Tabs,
  TabPane,
  // Carousel,
  CarouselItem,
  Tooltip,
  // --以上为原element组件
  Alert,
  Anchor,
  AnchorItem,
  Aside,
  Avatar,
  Backtop,
  Badge,
  Breadcrumb,
  BreadCrumbItem,
  Button,
  ButtonGroup,
  Calender,
  Card,
  Carousel,
  // CarouselItem,
  Cascader,
  CascaderPanel,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Collapse,
  CollapseItem,
  Container,
  DatePicker,
  Descriptions,
  // DescriptionsItem,
  Dialog,
  Divider,
  Drawer,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Empty,
  Footer,
  Form,
  FormItem,
  Header,
  Image,
  ZleInfiniteScroll,
  Input,
  InputNumber,
  Link,
  Main,
  NavMenu,
  PageHeader,
  Pagination,
  Popconfirm,
  Popover,
  Progress,
  Radio,
  RadioGroup,
  RadioButton,
  Rate,
  Result,
  Row,
  Col,
  Select,
  Option,
  OptionGroup,
  Skeleton,
  ZleSkeletonItem,
  Slider,
  Statistic,
  Steps,
  Switch,
  Table,
  TableColumn,
  Tabs,
  // TabPane,
  Tag,
  Timeline,
  TimelineItem,
  TimePicker,
  TimeSelect,
  ZleTooltip,
  Transfer,
  Tree,
  Upload,
  Autocomplete
]

Vue.prototype.$ELEMENT = { size: 'small', zIndex: 2000 }
components.forEach(component => {
  component && Vue.component(component.name, component)
})

Vue.use(InfiniteScroll)
Vue.use(Scrollbar)
Vue.use(Loading.directive)

Vue.prototype.$zlLoading = Loading.service
Vue.prototype.$zlMsgbox = MessageBox
Vue.prototype.$zlAlert = MessageBox.alert
Vue.prototype.$zlConfirm = MessageBox.confirm
Vue.prototype.$zlPrompt = MessageBox.prompt
Vue.prototype.$zlNotify = Notification
Vue.prototype.$zlMessage = Message
